sudo: required
dist: trusty
before_install:
- docker pull agonzalezro/pdflatex:latest
script:
- docker run --rm -v $(pwd):/output agonzalezro/pdflatex BDoranCV.tex
deploy:
  provider: releases
  api_key:
    secure: Y5yfXtUuvNC7kv/NOEyoTxd5HHqMSqWPiTpA1ZJr73sfBh0sSOBvAW2tTkZMzE3b1pZN8D1bkfUUdxW2hSDiJLr9hlQJ/vT4RdGVsOXkaLjpAfZ0XnzGAQw49spDz3Tp7k8T8lUNxAzfJqiUy3clJWFnS0pkhh+/RQtAE+l11DUS++7ksXJhhT537aoR73URvXgabS8FvG0q3UMFz7HHLLUlfoaSMUeN0BMISbJo6tP3CXP8lc0COT7dDRL7CuvbUuwISY6YaixfWXWWftzTxub1n0x5XvmEjglK3JUOHF8nU51uvGWcw21M/aGF83F6/w2xXCI32eDbs9/nPNe1dqgiuJoVrKvsFjgAI5fp59a/l6kTy3mU3+A/vxB63k1nctakEpyj+GZoMfXf5qD9G5trpFgPsRYWKQNIZ/vUlPHhMgbNR6LHTcW8TB9Whgigov2cFV0znCK97v5Nn3sBh91WxThV5rFpoX3eeld8PvB388wS0FqxKnZYVIhsRFc1Z0jvICXCzfDIrZbyXp+pRRhODlKIR8zGeYCLBvijI75wEc5JIOedJXpNWKmESkZmFXW4hlUQfN2yNPKlhLsvSfJNbQCxhemA/iKN0TAqzjVnhtbTdCg6ff0t14PitwmqeJk2IbMk+tXTWJ7aGX2qvx2MziJEwt7u7iEw54kg29A=
  file: "BDoranCV.pdf"
  on:
    repo: BenjaminDoran/doran_resume
    branch: setup-travis
